#!/usr/bin/env perl

# Because svn tags are the same as branches, git svn creates vestigial
# tracking branches for all svn tags, which looks disgusting.
# 
# For all remote branches called "tag/NAME", remove the branch and retag
# the parent with the tag name.

use Env qw(GIT_DIR);
chomp($git_dir = $GIT_DIR || qx(git rev-parse -q --git-dir) || die "unable to locate .git");

open(LOG, ">>$git_dir/svn/retag.log");

@branches = qx(git branch -r);
@svn_tags = grep(/^\s*tags\//, @branches);
foreach (@svn_tags) {
    if (($ref, $tag) = /^\s*(tags\/(.*))/) {
        ($commit, $parent) = split / /, qx(git show -s --pretty='format:%H %P' "$ref");

        print LOG "moving $tag from $commit -> $parent\n";
        print "moving $tag from $commit -> $parent\n";

        qx(git tag "$tag" "$parent");
        qx(git branch -rd "$ref");
    }
}

close(LOG);

